/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filmbook;

/**
 *
 * @author Java_sabah
 */
public class OperationFrame extends javax.swing.JFrame {

    /**
     * Creates new form BuyFrame
     */
    public OperationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        UserFilmPane = new javax.swing.JPanel();
        lblSearchFilm = new javax.swing.JLabel();
        txtOSearchFilm = new javax.swing.JTextField();
        btnOSearchFilm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAddToCart = new javax.swing.JButton();
        rbBuy = new javax.swing.JRadioButton();
        rbRent = new javax.swing.JRadioButton();
        lblOperationAlert = new javax.swing.JLabel();
        UserBookPane = new javax.swing.JPanel();
        lblSearchBook = new javax.swing.JLabel();
        txtOSearchBook = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        rbBuyBook = new javax.swing.JRadioButton();
        rbRentBook = new javax.swing.JRadioButton();
        UserCartPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSearchFilm.setText("Search Film : ");

        btnOSearchFilm.setText("Search");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnAddToCart.setText("Add to Cart");

        buttonGroup1.add(rbBuy);
        rbBuy.setText("Buy");

        buttonGroup1.add(rbRent);
        rbRent.setText("Rent");

        javax.swing.GroupLayout UserFilmPaneLayout = new javax.swing.GroupLayout(UserFilmPane);
        UserFilmPane.setLayout(UserFilmPaneLayout);
        UserFilmPaneLayout.setHorizontalGroup(
            UserFilmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserFilmPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserFilmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(UserFilmPaneLayout.createSequentialGroup()
                        .addComponent(lblSearchFilm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOSearchFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnOSearchFilm)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserFilmPaneLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(rbBuy)
                .addGap(18, 18, 18)
                .addComponent(rbRent)
                .addGap(32, 32, 32)
                .addComponent(lblOperationAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnAddToCart)
                .addGap(36, 36, 36))
        );
        UserFilmPaneLayout.setVerticalGroup(
            UserFilmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserFilmPaneLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(UserFilmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchFilm)
                    .addComponent(txtOSearchFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOSearchFilm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(UserFilmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddToCart)
                    .addComponent(rbBuy)
                    .addComponent(rbRent)
                    .addComponent(lblOperationAlert))
                .addContainerGap())
        );

        jTabbedPane1.addTab("FILMS", UserFilmPane);

        lblSearchBook.setText("Search Book : ");

        jButton1.setText("Search");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        buttonGroup1.add(rbBuyBook);
        rbBuyBook.setText("Buy");

        buttonGroup1.add(rbRentBook);
        rbRentBook.setText("Rent");

        javax.swing.GroupLayout UserBookPaneLayout = new javax.swing.GroupLayout(UserBookPane);
        UserBookPane.setLayout(UserBookPaneLayout);
        UserBookPaneLayout.setHorizontalGroup(
            UserBookPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserBookPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(UserBookPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserBookPaneLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rbBuyBook)
                        .addGap(18, 18, 18)
                        .addComponent(rbRentBook))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UserBookPaneLayout.createSequentialGroup()
                        .addComponent(lblSearchBook)
                        .addGap(18, 18, 18)
                        .addComponent(txtOSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        UserBookPaneLayout.setVerticalGroup(
            UserBookPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserBookPaneLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(UserBookPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchBook)
                    .addComponent(txtOSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UserBookPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbBuyBook)
                    .addComponent(rbRentBook))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BOOKS", UserBookPane);

        javax.swing.GroupLayout UserCartPaneLayout = new javax.swing.GroupLayout(UserCartPane);
        UserCartPane.setLayout(UserCartPaneLayout);
        UserCartPaneLayout.setHorizontalGroup(
            UserCartPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        UserCartPaneLayout.setVerticalGroup(
            UserCartPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CART", UserCartPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UserBookPane;
    private javax.swing.JPanel UserCartPane;
    private javax.swing.JPanel UserFilmPane;
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnOSearchFilm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblOperationAlert;
    private javax.swing.JLabel lblSearchBook;
    private javax.swing.JLabel lblSearchFilm;
    private javax.swing.JRadioButton rbBuy;
    private javax.swing.JRadioButton rbBuyBook;
    private javax.swing.JRadioButton rbRent;
    private javax.swing.JRadioButton rbRentBook;
    private javax.swing.JTextField txtOSearchBook;
    private javax.swing.JTextField txtOSearchFilm;
    // End of variables declaration//GEN-END:variables
}
